#!/usr/bin/env bash
# scripts/discover/codebase-brief.sh
# Phase 1 Discover: 生成 codebase-brief.md (~200 lines)
set -euo pipefail

TARGET="${1:-.}"
OUT_DIR="${2:-$TARGET/discovery}"
mkdir -p "$OUT_DIR"
OUT="$OUT_DIR/codebase-brief.md"

# Project info
PROJECT_NAME="$(basename "$(cd "$TARGET" && pwd)")"
{
  echo "# Codebase Brief: $PROJECT_NAME"
  echo ""
  echo "> Auto-generated by beautiful-codebase Phase 1 Discover"
  echo ""

  # Language stats
  echo "## Language Distribution"
  echo ""
  echo "| Language | Files | LOC |"
  echo "|----------|-------|-----|"
  for lang in py js ts go java rs rb php; do
    count=$(find "$TARGET" -name "*.$lang" -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/vendor/*" 2>/dev/null | wc -l)
    loc=$(find "$TARGET" -name "*.$lang" -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/vendor/*" -exec cat {} + 2>/dev/null | wc -l)
    [ "$count" -gt 0 ] && echo "| $lang | $count | $loc |"
  done
  echo ""

  # Top modules (by directory size)
  echo "## Top Modules (by file count)"
  echo ""
  find "$TARGET" -maxdepth 2 -type d -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/vendor/*" -not -path "*/.codegraph/*" \
    2>/dev/null | while read -r dir; do
    count=$(find "$dir" -type f 2>/dev/null | wc -l)
    [ "$count" -gt 5 ] && echo "- $(basename "$dir"): $count files"
  done | sort -t: -k2 -rn | head -15
  echo ""

  # Top-level structure
  echo "## Top-Level Structure"
  echo ""
  echo '```'
  find "$TARGET" -maxdepth 2 -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/vendor/*" -type d 2>/dev/null \
    | sed "s|$TARGET||" | sort | head -30
  echo '```'
  echo ""

  # Git info
  if git -C "$TARGET" rev-parse --git-dir >/dev/null 2>&1; then
    echo "## Git Info"
    echo ""
    echo "- Branch: $(git -C "$TARGET" rev-parse --abbrev-ref HEAD 2>/dev/null)"
    echo "- Recent commits: $(git -C "$TARGET" log --oneline -5 2>/dev/null | wc -l)"
    echo "- Total commits: $(git -C "$TARGET" rev-list --count HEAD 2>/dev/null)"
    echo "- Contributors: $(git -C "$TARGET" shortlog -s -n 2>/dev/null | head -10 | wc -l)"
    echo ""
    echo "### Top Contributors"
    echo ""
    git -C "$TARGET" shortlog -s -n 2>/dev/null | head -10
    echo ""

    echo "### Recent Activity (last 30 commits)"
    echo ""
    echo '```'
    git -C "$TARGET" log --oneline -30 2>/dev/null
    echo '```'
    echo ""
  fi

  echo "---"
  echo "_Generated at $(date -u +%Y-%m-%dT%H:%M:%SZ)_"
} > "$OUT"

echo "codebase-brief.md written ($(wc -l < "$OUT") lines, $(wc -c < "$OUT") bytes)"
